name: Test SplashKit Core Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        working-directory: projects/cmake
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make wget tar patch dos2unix diffutils ca-certificates mingw-w64-x86_64-ca-certificates mingw-w64-x86_64-gcc mingw-w64-x86_64-libpng cmake
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        working-directory: ./projects/cmake
        run: |
          cmake .
          make -j 2
      - name: Build
        working-directory: ./bin
        run: ./skunit_tests"