name: SplashKit Core Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: install-dependencies
        run: |
          cd /usr/share/fonts
          find .
          sudo apt-get -qq update
          sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
          sudo apt-get install -y libflac-dev libwebp-dev libvorbis-dev libpng-dev
          sudo apt-get install -y libcurl4-openssl-dev libmikmod2-dev
          sudo apt-get install -y libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: build
        working-directory: ./projects/cmake
        run: |
          CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 cmake .
          CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 make -j 2
      - name: execute
        working-directory: ./bin
        run: ./skunit_tests