name: SplashKit Core Windows
on: [push, pull_request]

jobs:
  test-win32-win64:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    defaults:
      run:
        shell: msys2 {0}
        working-directory: projects/cmake
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: git make wget tar patch dos2unix diffutils ca-certificates mingw-w64-${{ matrix.arch }}-ca-certificates mingw-w64-${{ matrix.arch }}-gcc mingw-w64-${{ matrix.arch }}-libpng cmake
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: build
        working-directory: ./projects/cmake
        run: |
          cmake .
          make -j 2
      - name: execute
        working-directory: ./bin
        run: ./skunit_tests"